version: "01"

services:
  app_proxy:
    environment:
      APP_HOST: cullinancloud-homepage_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/gethomepage/homepage:v1.1.1
    volumes:
      - ${APP_DATA_DIR}/data/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
